apiVersion: v1
kind: Secret
metadata:
  name: dotnet-secrets
  namespace: dotnet-stack
type: Opaque
data:
  rabbitmq-user: YWRtaW4=
  rabbitmq-password: bGFicGFzc3dvcmQxMjM=
  sql-user: c2E=
  sql-password: bGFicGEkJHcwcmQ=
